name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Set version numbmer"
        run: |
          sed -i '/VERSION = /c\VERSION = "${{ github.ref }}"' custom_components/garbage_colection/const.py
          sed -i 's|refs/heads/||' custom_components/garbage_colection/const.py
          sed -i 's|refs/tags/||' custom_components/garbage_colection/const.py

      # Pack the HACS dir as a zip and upload to the release
      - name: ZIP HACS Dir
        run: |
          cd /home/runner/work/test/test/custom_components/garbage_colection
          zip garbage_colection.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/test/test/custom_components/garbage_colection/garbage_colection.zip
          asset_name: garbage_colection.zip
          tag: ${{ github.ref }}
          overwrite: true
